### ISSUE TITLE
Create recommendation for the number of rounds based on player count

### ISSUE THREAD

**Issue by Chemscribbler** [Chemscribbler/aesopstables#11]
Currently I reference the Organized Play Guidelines, but putting it in the UI would probably be good.

**Comment by Aditi840** [comment]
hey can I work on this issue, just give me a rough idea on what needs to be done.

**Comment by Chemscribbler** [comment]
I'm not sure where this should go in the UI tbh - once round 1 is paired the TO probably should get a recommendation, and be able to reference it throughout. Also adding this to the documentation that users can look up at any time.

The table for the number of rounds is 
Single Sided Swiss Events: Casual
Players Swiss Rounds Cut
<12 6 None
<16 8 None, Top 3 or Top 4 Single Elim
<33 8 Top 4 Double Elim
<65 10 Top 8 Double Elim
<129 12 Top 8 Double Elim
>128 12 Top 16
Single Sided Swiss Events: Competitive
Players Swiss Rounds Cut
<16 6 None
<33 8 Top 4 Double Elim
<65 10 Top 8 Double Elim
<129 10 Top 8 Double Elim
<164 12 Top 16 Double Elim
>164 13 Top 16 Double Elim

**Comment by Aditi840** [comment]
@Chemscribbler  would you give me an idea on how to get started.

**Comment by Chemscribbler** [comment]
I think one easy option would be do something similar to what I did for the documentation pages - could probably go in the how to use documentation - so just editing the markdown would be a good start. You can find that (for now at least) here documentation/howto.md

**Comment by Aditi840** [comment]
@Chemscribbler , yaa sure

**Comment by Aditi840** [comment]
@Chemscribbler, will you check my pull request.

**Comment by Chemscribbler** [comment]
Apologies for being slow on this - I don't see a pull request?

**Comment by Aditi840** [comment]
https://github.com/Aditi840/aesopstables/pull/1 , here is my pull request

**Comment by Aditi840** [comment]
@Chemscribbler , Is my pull request visible now.

**Comment by Chemscribbler** [comment]
Closed with #19
