### ISSUE TITLE
Pronouns cannot be changed once initially set

### ISSUE THREAD

**Issue by dormio** [Chemscribbler/aesopstables#5]
TO (and users too, I think) are unable to change their pronouns. As TO, I am able to Edit names and the edit goes life to the Standings page; when I click Edit, the players' pronoun field on their registration page is blank, but other fields are filled in correctly.

**Comment by Chemscribbler** [comment]
Fixed with https://github.com/Chemscribbler/aesopstables/commit/db3f9072debfb6d2c0c5781f20bc259491f82bc0
