### ISSUE TITLE
Change identity selection to be sub-searchable

### ISSUE THREAD

**Issue by Chemscribbler** [Chemscribbler/aesopstables#9]
Ideally people entering their identities should be able to type substrings of the ID and have them highlighted or otherwise made easier to select. Currently Cobra compresses the dropdown to just show matching text. This would be a really nice feature to have. Probably would want to do it against the stripped text so people can type `Tao` and get `Tāo Salonga: Telepresence Magician`

**Comment by tzanetl** [comment]
Should be closed by https://github.com/Chemscribbler/aesopstables/pull/24
